service: My-API

package:
  exclude:
    - node_models

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/Abc

functions:
  create:
    handler: handler.create
    events:
      - httpApi:
          path: /items
          method: post

  get:
    handler: handler.get
    events:
      - httpApi:
          path: /items/{id}
          method: get

  update:
    handler: handler.update
    events:
      - httpApi:
          path: /items/{id}
          method: put

  delete:
    handler: handler.deleteItem
    events:
      - httpApi:
          path: /items/{id}
          method: delete

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Abc
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
